# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMessageCountDF <- function(filename, bufferSize, quiet = FALSE) {
    .Call('_RITCH_getMessageCountDF', PACKAGE = 'RITCH', filename, bufferSize, quiet)
}

getOrders_impl <- function(filename, startMsgCount, endMsgCount, bufferSize, quiet) {
    .Call('_RITCH_getOrders_impl', PACKAGE = 'RITCH', filename, startMsgCount, endMsgCount, bufferSize, quiet)
}

getTrades_impl <- function(filename, startMsgCount, endMsgCount, bufferSize, quiet) {
    .Call('_RITCH_getTrades_impl', PACKAGE = 'RITCH', filename, startMsgCount, endMsgCount, bufferSize, quiet)
}

getModifications_impl <- function(filename, startMsgCount, endMsgCount, bufferSize, quiet) {
    .Call('_RITCH_getModifications_impl', PACKAGE = 'RITCH', filename, startMsgCount, endMsgCount, bufferSize, quiet)
}

